name: Generate Banner

on:
  workflow_dispatch:
    inputs:
      device:
        description: Device codename
        required: true
        default: INGRES

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Chromium
        uses: browser-actions/setup-chrome@v1

      - name: Start HTTP server
        run: |
          python3 -m http.server 8000 &
          sleep 3

      - name: Generate banner
        run: |
          google-chrome \
            --headless \
            --disable-gpu \
            --hide-scrollbars \
            --window-size=1280,720 \
            --virtual-time-budget=5000 \
            --screenshot=banner.png \
            "http://127.0.0.1:8000/index.html?device=${{ github.event.inputs.device }}"

      - uses: actions/upload-artifact@v4
        with:
          name: banner
          path: banner.png